version: '3'
services:
  db:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "./db/data:/var/lib/postgresql/data"
    restart: always
  server:
    build: server/
    environment:
      - GIGACHAT_API_KEY=${GIGACHAT_API_KEY}
      - YACHAT_GPT_API_KEY=${YACHAT_GPT_API_KEY}
      - YACHAT_GPT_MODEL_URL=${YACHAT_GPT_MODEL_URL}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: python ./app/app.py
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
  client:
    build: client/
    command: sh -c "echo 'VITE_HOST= ${HOST}' > .env && npm run build && serve public -p 80"
    ports:
      - 80:80
    depends_on:
      - server
    restart: always