name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ./gigachat
            docker compose down
            git fetch

            echo "HOST= ${{ secrets.HOST }}" > .env

            echo "POSTGRES_USER= ${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD= ${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_USER= ${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD= ${{ secrets.POSTGRES_PASSWORD }}" >> .env

            echo "GIGACHAT_API_KEY= ${{ secrets.GIGACHAT_API_KEY }}" >> .env
            echo "YACHAT_GPT_API_KEY= ${{ secrets.YACHAT_GPT_API_KEY }}" >> .env
            echo "YACHAT_GPT_MODEL_URL= ${{ secrets.YACHAT_GPT_MODEL_URL }}" >> .env

            echo "SESSION_SECRET_KEY= ${{ secrets.SESSION_SECRET_KEY }}" >> .env

            docker compose build
            docker compose up -d
