name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            rm -rf ./gigachat
            git clone https://github.com/kotelnikov-vladislav/gigachat.git
            cd ./gigachat
            docker compose down
            docker compose build
            docker compose up -d
