name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ./gigachat
            docker compose down
            git pull https://github.com/kotelnikov-vladislav/gigachat.git

            echo "VITE_HOST= ${{ secrets.HOST }}" > ./client/.env

            echo "POSTGRES_USER= ${{ secrets.POSTGRES_USER }}" >> .env_db
            echo "POSTGRES_PASSWORD= ${{ secrets.POSTGRES_PASSWORD }}" >> .env_db

            echo "DEPLOY= true" >> ./server/.env
            echo "POSTGRES_USER= ${{ secrets.POSTGRES_USER }}" >> ./server/.env
            echo "POSTGRES_PASSWORD= ${{ secrets.POSTGRES_PASSWORD }}" >> ./server/.env
            echo "GIGACHAT_API_KEY= ${{ secrets.GIGACHAT_API_KEY }}" >> ./server/.env
            echo "YACHAT_GPT_API_KEY= ${{ secrets.YACHAT_GPT_API_KEY }}" >> ./server/.env
            echo "YACHAT_GPT_MODEL_URL= ${{ secrets.YACHAT_GPT_MODEL_URL }}" >> ./server/.env
            echo "SESSION_SECRET_KEY= ${{ secrets.SESSION_SECRET_KEY }}" >> ./server/.env
            docker compose build
            docker compose up -d
