name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ./gigachat
            docker compose down
            git pull https://github.com/kotelnikov-vladislav/gigachat.git
            echo "VITE_HOST= ${{ secrets.HOST }}" > ./client/.env
            echo "CREDENTIALS= ${{ secrets.CREDENTIALS }}" > ./server/.env
            docker compose build
            docker compose up -d
